In [1]:
import cv2

In [2]:
imagem = cv2.imread('workplace-1245776_1920.jpg')

In [3]:
windows_name = 'image'
cv2.imshow(windows_name, imagem)

cv2.waitKey(0)

-1

In [4]:
cv2.destroyAllWindows()

In [5]:
detector_face = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

imagem_cinza = cv2.cvtColor(imagem, cv2.COLOR_BGR2GRAY)
cv2.imshow(windows_name, imagem_cinza)

cv2.waitKey(0)

-1

In [6]:
cv2.destroyAllWindows()

In [7]:
deteccoes = detector_face.detectMultiScale(imagem_cinza, scaleFactor=1.3, minSize=(30,30))
deteccoes


array([[1635,  156,  147,  147],
       [ 284,  262,  114,  114],
       [ 928,  491,  171,  171],
       [1149,  260,  129,  129],
       [ 222,  507,  151,  151]])

In [8]:
for (x, y, l, a) in deteccoes:
    cv2.rectangle(imagem, (x, y), (x + l, y + a), (0,255,0), 2)
    
cv2.imshow(windows_name, imagem)
cv2.waitKey(0)

-1

In [9]:
cv2.destroyAllWindows()

In [10]:
## exercicio

In [11]:
pessoas = cv2.imread('pessoas.jpg')

#cv2.imshow(windows_name, pessoas)
#cv2.waitKey(0)
#cv2.destroyAllWindows()

In [12]:
detector_body = cv2.CascadeClassifier('fullbody.xml')
pessoas_cinzas = cv2.cvtColor(pessoas, cv2.COLOR_BGR2GRAY)

cv2.imshow(windows_name, pessoas_cinzas)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
deteccoes_pessoas = detector_body.detectMultiScale(pessoas_cinzas, scaleFactor=1.01, minSize=(40,140))
print(deteccoes_pessoas)

[[ 71  62  93 186]
 [325  70  86 171]
 [264  78  79 158]
 [525  88  77 153]
 [461  60  89 178]
 [138  70  84 169]
 [197  52  93 186]
 [ 12  64  90 179]
 [396  60  89 177]]


In [14]:
for (x, y, l ,a) in deteccoes_pessoas:
    cv2.rectangle(pessoas, (x,y), (x+l, y+a), 2)
    
cv2.imshow(windows_name, pessoas)
cv2.waitKey(0)
cv2.destroyAllWindows()

## reconhecimento facial
treinamento

In [15]:
from PIL import Image
import numpy as np
import os

In [16]:
def dados_imagem():
    caminhos = [os.path.join(r'yalefaces\train', f) for f in os.listdir(r'yalefaces\train')]
    faces = []
    ids = []
    for caminho in caminhos:
        imagem = Image.open(caminho).convert('L')
        imagem_np = np.array(imagem, 'uint8')
        id = int(os.path.split(caminho)[1].split('.')[0].replace('subject', ''))
        ids.append(id)
        faces.append(imagem_np)
    
    return np.array(ids), faces

In [17]:
ids, faces = dados_imagem()

In [18]:
print(ids)

[ 1  1  1  1  1  1  1  1  1  2  2  2  2  2  2  2  2  2  3  3  3  3  3  3
  3  3  3  4  4  4  4  4  4  4  4  4  5  5  5  5  5  5  5  5  5  6  6  6
  6  6  6  6  6  6  7  7  7  7  7  7  7  7  7  8  8  8  8  8  8  8  8  8
  9  9  9  9  9  9  9  9  9 10 10 10 10 10 10 10 10 10 11 11 11 11 11 11
 11 11 11 12 12 12 12 12 12 12 12 12 13 13 13 13 13 13 13 13 13 14 14 14
 14 14 14 14 14 14 15 15 15 15 15 15 15 15 15]


In [19]:
print(faces[0])

[[130 130 130 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 252 255 255]
 [255 255 255 ... 255 255 255]
 [ 68  68  68 ...  68  68  68]]


In [20]:
lbph = cv2.face.LBPHFaceRecognizer_create()
lbph.train(faces, ids)
lbph.write('classificadorLBPH.yml')